CREATE TABLE IF NOT EXISTS FUNKOS (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     cod UUID NOT NULL DEFAULT RANDOM_UUID(),
     MyId BIGINT,
     nombre VARCHAR(255),
     modelo VARCHAR(255),
     precio DOUBLE PRECISION,
     fecha_lanzamiento DATE,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);